src/Entity/Job.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Filesystem\Filesystem;

/**
 * @ORM\Entity(repositoryClass="App\Repository\JobRepository")
 */
class Job implements \JsonSerializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(allowNull = true)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(allowNull = false)
     */
    private $constraint_mining;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Please, upload data in the .dat format")
     * @App\Validator\Constraints\DatFileFormat
     * @Assert\File(
     *  mimeTypes={ "text/plain", "text/csv" }, 
     *  mimeTypesMessage="!The mime type of the file is invalid ({{ type }}). Allowed mime types are {{ types }}."
     * )
     */
    private $datasheet;

    /**
     * @ORM\Column(type="integer")
     */
    private $frequency;

    /**
     * @ORM\Column(type="datetime")
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $endDate;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="jobs")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="array")
     */
    private $columns = [];

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nbLines;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Alert", mappedBy="job", cascade={"persist", "remove"})
     */
    private $alert;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getConstraintMining(): ?string
    {
        return $this->constraint_mining;
    }

    public function setConstraintMining(string $constraint_mining): self
    {
        $this->constraint_mining = $constraint_mining;

        return $this;
    }

    public function getDatasheet(): ?string
    {
        return $this->datasheet;
    }

    public function setDatasheet(string $datasheet): self
    {
        $this->datasheet = $datasheet;

        return $this;
    }

    public function deleteDatasheet(string $datasheetsDir): self
    {
        $fileSystem = new Filesystem();
        $InputDatasheetPath = $datasheetsDir.'/'.$this->getInputDatasheet();
        $OutputDatasheetPath = $datasheetsDir.'/'.$this->getOutputDatasheet();
        $fileSystem->remove([
            $InputDatasheetPath, 
            $OutputDatasheetPath
        ]);

        return $this;
    }

    public function getInputDatasheet(): ?string
    {
        return pathinfo($this->datasheet, PATHINFO_FILENAME).'.in.csv';
    }

    public function getOutputDatasheet(): ?string
    {
        return pathinfo($this->datasheet, PATHINFO_FILENAME).'.out.csv';
    }

    public function getFrequency(): ?int
    {
        return $this->frequency;
    }

    public function setFrequency(int $frequency): self
    {
        $this->frequency = $frequency;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate = null): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getColumns(): ?array
    {
        return $this->columns;
    }

    public function getColumn($index): ?string
    {
        return $this->columns[$index-1];
        return $index-1;
    }

    public function setColumns(array $columns): self
    {
        $this->columns = $columns;

        return $this;
    }

    public function getNbLines(): ?int
    {
        return $this->nbLines;
    }

    public function setNbLines(int $nbLines): self
    {
        $this->nbLines = $nbLines;

        return $this;
    }

    public function getAlert(): ?Alert
    {
        return $this->alert;
    }

    public function setAlert(Alert $alert): self
    {
        $this->alert = $alert;

        // set the owning side of the relation if necessary
        if ($alert->getJob() !== $this) {
            $alert->setJob($this);
        }

        return $this;
    }

    public function getResults(string $datasheetsDir, $excludedColumns = []): ?array
    {
        $results = unserialize(
                file_get_contents(
                    $datasheetsDir.'/'.$this->getOutputDatasheet()
                )
            );                

        foreach ($results as $k => $line) {

            $present = False;

            foreach($excludedColumns as $excludedColumn)
            {
                if(
                    in_array($excludedColumn."+", $line['columns']) 
                    || in_array($excludedColumn."-", $line['columns']) 
                )
                {
                    $present = True;
                }
            }

            if($present)
            {
                unset($results[$k]);
            }
        }
    
        return $results;
    }

    public function jsonSerialize() : array
    {
        return [
            'id'                => $this->id,
            'columns'           => $this->columns,
            'nbLines'           => $this->nbLines,
            'title'             => $this->title,
            'datasheet'         => $this->datasheet,
            'frequency'         => $this->frequency,
            'constraint_mining' => $this->constraint_mining,
            'startDate'         => date_format($this->startDate, 'Y-m-d H:i:s'),
            'endDate'           => date_format($this->endDate, 'Y-m-d H:i:s'),
            'user'              => $this->user->getId(),
            'columns'           => $this->columns,
        ];
    }

}

src/Form/JobType.php
<?php

namespace App\Form;
use App\Entity\Job;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\OptionsResolver\OptionsResolver;

use App\Services\ConstraintMining;

class JobType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
        ->add('title', TextType::class, [
            'required'   => true
        ])
        ->add('constraint_mining', ChoiceType::class, [
            'required'   => true,
            'choices'  => array_merge(
                ['Choose a temporal constraint between objects ...' => 0],
                ConstraintMining::$constraintMiningChoices
            )
        ])
        ->add('frequency', IntegerType::class, [
            'required'   => true
        ])
        ->add('datasheet', FileType::class, [
            'required'   => true,
            'label' => 'Datasheet (.dat)', // see in templates/job/list.html.twig for link
        ]) 
        ->add('save', SubmitType::class, [
            'label' => 'Submit Job', 
            'attr' => [
                'class' => 'btn btn-primary float-right'
            ]
        ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Job::class,
        ]);
    }
}

src/Controller/JobController.php
<?php

namespace App\Controller;

use App\Entity\Job;
use App\Entity\Alert;
use App\Entity\User;
use App\Form\JobType;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;

use Enqueue\Client\ProducerInterface;

use App\Services\ConstraintMining;


class JobController extends AbstractController
{
    /**
     * @Route("/job/{id<\d+>}", name="job", defaults={"id"=0})
     * @IsGranted("ROLE_USER")
     */
    public function list(
        Request $request, 
        ProducerInterface $producer, 
        $id, 
        AuthorizationCheckerInterface $authChecker,
        ParameterBagInterface $params)
    {
        // job submision
        $job = new Job();
        $form = $this->createForm(JobType::class, $job, [
            'csrf_protection' => false,
            'attr' => ['id' => 'job-form']
        ]);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) 
        {
            $job = $form->getData();
            $datasheet = $form->get('datasheet')->getData();
            $datasheetName = md5(uniqid());
            try {
                $datasheet->move(
                    $this->getParameter('datasheets_dir'),
                    $datasheetName.'.in.csv'
                );
                
            } catch (FileException $e) {
                // ... handle exception if something happens during file upload
            }
            $job->setDatasheet($datasheetName);
            $job->setUser($this->getUser());
            $job->setStartDate(new \DateTime('now'));        

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($job);
            $entityManager->flush();
            
            $producer->sendEvent(
                'JobTopic', 
                $job->getId().';'.$this->getUser()->getEmail()
            );
            
            return $this->render('job/inc/card.html.twig', [
                'job' => $job,
                'constraintMiningChoices' => array_flip(ConstraintMining::$constraintMiningChoices),
                'maxLinesToShow' => $params->get('max_lines_to_show'),
            ]);
        }

        // filter user jobs
        if(false === $authChecker->isGranted('ROLE_ADMIN'))
        {
            $criteria = ['user' => $this->getUser()];
        }
        // all jobs for admin
        else
        {
            if($id)
            {
                $user = $this->getDoctrine()
                ->getRepository(User::class)
                ->find($id);
                dump($user);
                $criteria = ['user' => $user];
            }
            else
            {
                $criteria = [];
            }
        }

        $orders = [
            'startDate' => 'DESC',
            'endDate' => 'DESC'
        ];

        $jobs = $this->getDoctrine()
        ->getRepository(Job::class)
        ->findBy($criteria, $orders);

        return $this->render('job/list.html.twig', [
            'form' => $form->createView(),
            'jobs' => $jobs,
            'constraintMiningChoices' => array_flip(ConstraintMining::$constraintMiningChoices),
            'maxLinesToShow' => $params->get('max_lines_to_show'),
        ]);
    }

    /**
     * @Route(
     *  "/job/show/{id<\d+>}",
     *  options = { "expose" = true },
     *  name="job_show",
     * )
     * @IsGranted("ROLE_USER")
     */
    public function show($id, AuthorizationCheckerInterface $authChecker, ParameterBagInterface $params)
    {
        // display user job
        if(false === $authChecker->isGranted('ROLE_ADMIN'))
        {
            $job_criteria = [
                'id' => $id,
                'user' => $this->getUser(),
            ];
        }
        // display any user job for admin
        else
        {
            $job_criteria = [
                'id' => $id,
            ];
        }

        $job = $this->getDoctrine()
        ->getRepository(Job::class)
        ->findOneBy($job_criteria);

        // mark as read if first show for user
        if(false === $authChecker->isGranted('ROLE_ADMIN'))
        {
            $job->getAlert()->setReaded(True);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($job);
            $entityManager->flush();
        }

        return $this->render('job/show.html.twig', [
            'job' => $job,
            'constraintMiningChoices' => array_flip(ConstraintMining::$constraintMiningChoices),
            'maxLinesToShow' => $params->get('max_lines_to_show'),
        ]);
    }

    /**
     * @Route(
     *  "/job/delete/{id<\d+>}",
     *  name="job_delete",
     * )
     * @IsGranted("ROLE_USER")
     */
    public function delete($id, AuthorizationCheckerInterface $authChecker)
    {

        // display user job
        if(false === $authChecker->isGranted('ROLE_ADMIN'))
        {
            $job_criteria = [
                'id' => $id,
                'user' => $this->getUser(),
            ];
        }
        // display any user job for admin
        else
        {
            $job_criteria = [
                'id' => $id,
            ];
        }

        $job = $this->getDoctrine()
        ->getRepository(Job::class)
        ->findOneBy($job_criteria);

        $job->deleteDatasheet($this->getParameter('datasheets_dir'));
        
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($job);
        $entityManager->flush();

        return $this->redirectToRoute('home');
    }

}

templates/job/inc/card.html.twig
<div id="job-{{ job.id }}" class="card border-success mb-3">

    <div class="card-header">
        
        <span class="fold">
            <i class="fas fa-minus-square"></i>
        </span>

        <span class="title-icon">
            {% if job.columns | length == 0 %}
            <i class="fas fa-spinner fa-pulse"></i>
            {% else %}
            <i class="fas fa-cog"></i>
            {% endif %}
        </span>
        
        {{ job.title }}
        
        {% if job.alert is defined and job.alert and not job.alert.readed %}
        <span class="badge badge-success">new</span>
        {% endif %}
        
        <div class="float-right">

            {% if is_granted('ROLE_ADMIN') %}
            <a class="btn btn-primary btn-circle btn-sm"
                href="{{ path('job', { 'id': job.user.id }) }}">
                <i class="far fa-user-circle"></i> {{ job.user.email }}
            </a>
            {% endif %}
        

            {% if job.nbLines >= maxLinesToShow %}
            <button type="button" class="unshow btn btn-warning btn-circle btn-sm"
                data-toggle="tooltip" 
                data-placement="top"
                alt="too many lines to show results, download csv ouput"
                title="too many lines to show results, download csv ouput">
                <i class="fas fa-eye-slash"></i>
            </button>
            {% else %}
            <a class="btn btn-success btn-circle btn-sm"                
                href="{{ path('job_show', { 'id': job.id }) }}">
                <i class="fas fa-eye"></i>
            </a>
            {% endif %}
        
            <a class="btn btn-danger btn-circle btn-sm"
                href="{{ path('job_delete', { 'id': job.id }) }}"
                onclick="return confirm('Are you sure?')">
                <i class="fas fa-trash"></i>
            </a>

        </div>

    </div>

    <div class="card-body"> <!-- style="display: none"-->

        <div class="container">
            <div class="row">
                
                <div class="col-sm-6">

                    <i class="fas fa-chart-bar"></i> 
                    {{ constraintMiningChoices[job.constraintMining] }}
                    
                </div>

                <div class="col-sm-2">

                    <i class="fab fa-font-awesome-flag"></i> 
                    frequency {{ job.frequency }}

                </div>

                <div class="col-sm-2">

                    <span class="to-update" 
                        {% if job.columns | length == 0 %}style="display: none;"{% endif %}>
                        <i class="fas fa-grip-horizontal"></i>
                        <span class="nb-lines">
                            {{ job.nbLines }}
                        </span> 
                        lines
                    </span>

                </div>
                
                <div class="col-sm-2">

                    <span class="to-update" 
                        {% if job.columns | length == 0 %}style="display: none;"{% endif %}>
                        <i class="fas fa-columns"></i> 
                        <span class="columns">
                            {{ job.columns | length }}
                        </span> 
                        columns
                    </span>

                </div>
            
            </div>
            
            <div class="row">
                <div class="col-sm-4">

                    <span class="to-update" {% if job.columns | length == 0 %}style="display: none;"{% endif %}>
                        <i class="fas fa-check-circle"></i> processed in 
                        <span class="processed-in" >
                            {% if job.endDate %}
                                {{ job.endDate.diff(job.startDate)|date("%I:%Ss") }}
                            {% endif %}
                        </span>
                    </span>

                </div>

                <div class="col-sm-4">

                    <i class="fas fa-calendar-check"></i>
                    submitted at {{ job.startDate|date("Y/m/d H:i:s") }}

                </div>
                
                <div class="col-sm-4">

                    <div class="float-right">
                        <a class="btn btn-primary btn-circle btn-sm"
                            href="{{ path('job_datasheet_input', { 'id': job.id }) }}">
                            <i class="fas fa-file-csv"></i> input 
                        </a>
        
                        <span class="to-update" {% if job.columns | length == 0 %}style="display: none;"{% endif %}>
                            <a class="btn btn-primary btn-circle btn-sm"
                                href="{{ path('job_datasheet_output', { 'id': job.id }) }}">
                                <i class="fas fa-file-csv"></i> result
                            </a>
                        </span>            

                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

templates/job/inc/columns.html.twig
<div class="card border-success">
    <div class="card-header">
        Columns
    </div>
    <div class="card-body">
        
        <div class="text-center">
            <button id="check-all" class="btn btn-secondary" alt="check all" title="check all">
                <i class="fas fa-check-circle"></i>
            </button>
            
            <button id="uncheck-all" class="btn btn-secondary" alt="uncheck all" title="uncheck all">
                <i class="far fa-check-circle"></i>
            </button>

            <button id="toggle-all" class="btn btn-secondary" alt="toggle all" title="toggle all">
                <i class="fas fa-toggle-off"></i>
            </button>
        </div>

        <form  id="columns" action="{{ path('job_datasheet_output', { 'id': job.id })}}" method="POST">

            <ul>
                {% for key, column in job.columns %}
                <li>
                    <input name="selected_columns[]" value="{{ key+1 }}" type="checkbox" checked="checked" /> 
                    {{ column }}
                    <input name="columns[]" value="{{ key+1 }}" type="hidden" />
                </li>
                {% endfor %}
            </ul>

            <div class="text-center">
                <button type="submit" 
                    id="results-task-{{ job.id }}" 
                    class="btn btn-secondary">
                    <i class="fas fa-save"></i> save as csv
                </button>
            </div>

        </form>
    </div>
</div>

templates/job/inc/modal.html.twig
<div class="modal fade" id="jobModal" tabindex="-1" role="dialog" aria-labelledby="jobModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered  modal-sm" role="dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="jobModalLabel">Processing ...</h5>
      </div>
      <div class="modal-body text-center">
        <i class="fas fa-cog fa-spin"></i>
      </div>
    </div>
  </div>
</div>

templates/job/inc/results.html.twig
<div class="card border-success">
    <div class="card-header">
        Results (<span id="results-count"></span>)
    </div>
    <div class="card-body">
        <table class="table">
        <thead>
            <tr>
                {% if job.constraintMining == "consecutive_with_tids" %}
                <th class="col-md-5">
                {% else %}
                <th class="col-md-9">
                {% endif %}
                    Trends 
                    <span id="trends-sort">
                        <i class="fas fa-sort-down"></i>
                    </span>
                </th>
                <th class="col-md-2">
                    Frequency
                    <span id="frequency-sort">
                        <i class="fas fa-sort-down"></i>
                    </span>
                </th>
                {% if job.constraintMining == "consecutive_with_tids" %}
                <th class="col-md-4">
                    Tids
                </th>
                {% endif %}
            </tr>
        </thead>
        <tbody id="results">
        {% for line in job.results(datasheets_dir) %}
        <tr>
            <td class="columns trends">
            {% for c in line.columns %}
                {% if c | slice (0,-1) matches '/^\\d+$/' %}
                <span class="index">
                    {{ c | slice (0,-1) }}
                    {{ c | slice (-1) }}
                </span>

                {% if c | slice (-1) == "+" %}
                <span class="badge badge-success">
                {% else %}
                <span class="badge badge-danger">
                {% endif %}
                    {{ job.column(c | slice (0,-1)) }}
                    {% if c | slice (-1) == "+" %}
                    <i class="fas fa-arrow-circle-up"></i>
                    {% else %}
                    <i class="fas fa-arrow-circle-down"></i>
                    {% endif %}
                {% endif %}                    
                </span>
            
            {% endfor %}
            </td>
            <td class="columns frequency">
                <span class="badge badge-info">
                    {{ line.frequency }}
                </span>
            </td>
            {% if job.constraintMining == "consecutive_with_tids" %}
            <td class="columns tids">
                {% for t in line.tids %}
                <span class="badge badge-warning">
                    {{ t }}
                </span>
                {% endfor %}
            </td>
            {% endif %}
        </tr>
        {% endfor %}
        </tbody>
        </table>
    </div>
</div>